### ISSUE TITLE
Steam Guard

### ISSUE THREAD

**Issue by gausie** [ch1bo/garmin-otp-authenticator#1]
Just looking at the code (and with a limited understanding of Steam Guard) would the `hotp()` code look something like

```javascript
const STEAM_ALPHABET = ['2', '3', '4', '5', '6', '7', '8', '9', 'B', 'C', 'D', 'F', 'G', 'H', 'J', 'K', 'M', 'N', 'P', 'Q', 'R', 'T', 'V', 'W', 'X', 'Y'];

function hotp(key, counter, digit, steam) {
  if (digit > 9) {
    digit = 9;
  }
  var data = new [8];
  for (var i = data.size() - 1; i >= 0; i--) {
    data[i] = counter & 0xff;
    counter = counter >> 8;
  }
  var h = hmacSHA1(key, data);
  var t = truncate(h);

  var n = t % DIGITS[digit];
  var code = n.toString();

  var result = '';

  if (steam) {
    for (var i = 0; i < code.length(); i++) {
      var value = code[i];
      result = result + STEAM_ALPHABET[value];
    }
  } else {
    while (result.length() < digit) {
      result = "0" + result;
    }
  }

  return result;
}
```

or would the truncation have to change too?

**Comment by ch1bo** [comment]
According to the sources of TheZ3ro's comment on https://github.com/keepassxreboot/keepassxc/issues/594 this is not much more complicated than that yes.

I'd change the interface of the OTP functions to return the numeric value and decide about code generation outside though. As a side note `code` is a string, thus `code[i]` would be a char and not suitable for array access in MonkeyC AFAIK. 

Any suggestions in how to make it available in the UI, i.e. when to choose between styles and/or change after creating an entry?

**Comment by heavy7** [comment]
I'm waiting for Steam Guard

**Comment by ch1bo** [comment]
I gave it a shot on this and fail now to get my hands on my Steam guard secret key. When activating it from the mobile App, the base32 secret key is not shown to the user. Does anyone have an idea in how to acquire those?

**Comment by heavy7** [comment]
On android secret key hey here /data/data/com.valvesoftware.steam.community/fales Need root.

**Comment by ch1bo** [comment]
Thanks, I'll root my phone and give it a shot as soon as I have time. If you are keen to try it out before, you can checkout the branch `steam-authenticator` and build the app using garmins connect iq sdk. Should be just `make` or `make release` when the compiler is in your path.

**Comment by alexanderadam** [comment]
Is this issue still relevant?
Because [it explicitly says Steam Guard support in the description](https://github.com/ch1bo/garmin-otp-authenticator#features). :wink:

**Comment by ch1bo** [comment]
@alexanderadam Thanks for pointing this out, steam guard is indeed supported.
