### ISSUE TITLE
Support for Venu SQ & SQ Music

### ISSUE THREAD

**Issue by m4g0r** [ch1bo/garmin-otp-authenticator#17]
Is there some limitations to this devices or could they be supported?

**Comment by ch1bo** [comment]
Sorry that it took so long, but I finally released version 1.2.0 which supports the Venu Sq. I only tested it in the simulator, so have a try and feel free to re-open this issue if you have any problems with this device.

https://apps.garmin.com/en-US/apps/c601e351-9fa8-4303-aead-441251559064#0
