### ISSUE TITLE
Support for Forerunner 935

### ISSUE THREAD

**Issue by greenfoo** [ch1bo/garmin-otp-authenticator#18]
Would it be possible to add support to FR935? Or is there something in the (older) API preventing this?

Thanks!

**Comment by ch1bo** [comment]
No, I just took forever to have another go on setting up the SDK and build a version for your device. Version 1.2.0 is released now and should support your device! Feel free to re-open this issue if it does not run properly.

https://apps.garmin.com/en-US/apps/c601e351-9fa8-4303-aead-441251559064#0

P.S: Your device seems to have up/down buttons which can now be used for quick switching providers :)
