### ISSUE TITLE
Long Press & Device Hotkeys Fenix

### ISSUE THREAD

**Issue by TransRapid** [ch1bo/garmin-otp-authenticator#19]
If you are on a device without a touch screen, the app essentially is non functional as far as not being able to long press the keys for the app itself, without triggering a device wide shortcut/hotkey. 

This is for a Fenix 6, not sure if anyone has run into this issue. Can we potentially implement another method of confirmation for non touch screen devices? The issue with removing shortcuts is that the long press for the start activity is one of the easier hotkeys to use.

Maybe this is a limitation. I can't do anything beyond put in letters. Maybe a software check/complete entry/submit button along the keys? That is the case elsewhere on my device where characters are manually entered on the device itself.

**Comment by ch1bo** [comment]
The `TextInput` view is using the `Menu` behavior for confirming and continuing. In case for the fenix 6, this is a long press on the left-hand button, right? Do I understand yo correctly, that this behavior is conflicting with a shortcut to start an activity?

**Comment by ch1bo** [comment]
@TransRapid Is this still an issue for you?
