### ISSUE TITLE
More devices

### ISSUE THREAD

**Issue by wouterch** [ch1bo/garmin-otp-authenticator#2]
Would it be possible to add more compatible devices to the list, so I can download this app from the Connect IQ store on my Vivoactive 3?

**Comment by ch1bo** [comment]
Yeah, but I can only test them in the simulator.

However my top-prioity for the next release is to get a proper import/export or backup/restore implemented as ConnectIQ seems to not migrate application storage on upgrades.

I would then just release the next version also for the vivoactive 3

⁣Sent from TypeApp ​

**Comment by justindra** [comment]
@ch1bo happy to help out on getting it working on the Vivoactive 3 if you point me in the right direction. As I would also like to have it on mine.

**Comment by ch1bo** [comment]
Vivoactive 3 is supported since version `1.0.0`
