### ISSUE TITLE
Any chance for a prg file?

### ISSUE THREAD

**Issue by CharlieBrown12** [ch1bo/garmin-otp-authenticator#20]
Love the idea that your authenticator app can be used without the Garmin Connect/Express settings page...
However - Garmin changed apps behaviour, in a sense that PRG files are encrypted and inaccessible to users, so one still has to use Connect/Express at least to install the file.

Is there any chance to share the PRG file?
I am using FR945

Many thanks

**Comment by ch1bo** [comment]
I created a github release holding the `.iq` file, IIRC that can also be sideloaded: https://github.com/ch1bo/garmin-otp-authenticator/releases/tag/1.2.0
