### ISSUE TITLE
Battery drain?

### ISSUE THREAD

**Issue by ch1bo** [ch1bo/garmin-otp-authenticator#23]
Multiple users support subjectively higher battery usage and suspect the glance view being the culprit.

Given that this feature was added only recently, that would make sense.

Starting points:
* GlanceView does not stop re-calculating codes
* GlanceView updates too often
* Have a simple non-code-calculating GlanceView could be a workaround and was also requested by a user

**Comment by v0y4g3r** [comment]
Does it help to disable "show first key on glance view"?

**Comment by ch1bo** [comment]
Not reproducible and recently major rewrite. Re-open if still suspected
