### ISSUE TITLE
Support for Forerunner 255/955

### ISSUE THREAD

**Issue by liviuvalsan** [ch1bo/garmin-otp-authenticator#26]
Hi,

Thanks for the great widget!  Would it be possible to add support for Forerunner 255/955?

Thanks a lot in advance.

**Comment by liviuvalsan** [comment]
Hi,

It seems that there is already a pull request for adding support for Forerunner 955: https://github.com/ch1bo/garmin-otp-authenticator/pull/25

Given that the Fenix 7 is already supported and that the Forerunner 955 is basically a Fenix 7 with another body, adding support for the Forerunner 955 should be as simple as adding it to the list of supported products inside the manifest.

Thanks again for the great widget!

**Comment by ch1bo** [comment]
Published version 1.6.0 into the ConnectIQ store which adds Forerunner 955 support.
