### ISSUE TITLE
Support for Instinct 2X Solar

### ISSUE THREAD

**Issue by fibrewire** [ch1bo/garmin-otp-authenticator#28]
Hi there, I'm hoping to see support for the Instinct 2X solar. It has the 176 x 176 monochrome display. I'm happy to QA when this gets pushed out.

**Comment by fibrewire** [comment]
Hi just looking to see if there is an update for this? Thank you!

**Comment by ch1bo** [comment]
Published version 1.6.0 into the ConnectIQ store which adds Instinct 2X support.

**Comment by ubipo** [comment]
Only tested on Instinct 2S. So yeah, physical test on the X would be great!
