### ISSUE TITLE
add support for enduro 3

### ISSUE THREAD

**Issue by jpph** [ch1bo/garmin-otp-authenticator#38]
Hello, thank you for the addition for the Marcq gen 2. I will receive soon in the mail a enduro 3 too. I see you already update to Fenix 8, I think it should be almost same for enduro 3 ?

Thank you for your great app!

**Comment by ch1bo** [comment]
Just pushed a new release 2.2.0 which includes support for the enduro 3!

Tested briefly with the simulator. If you encounter any issues with the real device, feel free to open an issue here :handshake:
