### ISSUE TITLE
Support for Garmin Forerunner 945

### ISSUE THREAD

**Issue by alexanderadam** [ch1bo/garmin-otp-authenticator#4]
It would be great to add support for the Garmin Forerunner 945.

Thank you so much for your work :pray:

**Comment by ch1bo** [comment]
There is no Forerunner 745 according to https://developer.garmin.com/connect-iq/compatible-devices/. Do you mean the 645 or the 735?

**Comment by alexanderadam** [comment]
Sorry, you were right. It's the 945!

**PS:** There's also a 745 according to the [Garmin website](https://buy.garmin.com/de-DE/DE/p/713363/pn/010-02445-10)

**Comment by ch1bo** [comment]
Alright, am on it .. but might take some days as I need to upgrade the SDK and add `:glance` support (same for fenix 6 series) as the simulator crashes when loading the full widget on glance.

**Comment by alexanderadam** [comment]
Awesome! But no hurry — take you time and always remember that your personal health comes first.

**Comment by ch1bo** [comment]
Added support for the Forerunner 945 with version `1.0.3`. Please try it and if something is not working, feel free to re-open this ticket. Other than that, I'd appreciate a positive review in the connectiq store :)
