### ISSUE TITLE
Compatible with Venu?

### ISSUE THREAD

**Issue by jhowzr** [ch1bo/garmin-otp-authenticator#5]
Could this be updated to support the Venu?

**Comment by ch1bo** [comment]
Yes, I just added it and tried it in the simulator so far. Will release a new version within the next days which will add support for the venu as well. However I can only test it in the sim and will need your feedback if anything does not work!

**Comment by jhowzr** [comment]
Wow! Thanks. I didn't expect you to get it done so quickly. I just put it
into the system as a reminder. You're awesome!

**Comment by ch1bo** [comment]
The venu is supported now with version `1.0.3`. As I do not have this watch myself, I would appreciate if you re-open this ticket should you face any problems and of course a positive review on the store is always welcome :)
