### ISSUE TITLE
Status bar

### ISSUE THREAD

**Issue by alexanderadam** [ch1bo/garmin-otp-authenticator#6]
I was using [OTP Auth](https://apps.garmin.com/en-US/apps/f341dc64-bf39-4224-9c03-14d2434354a4) before I migrated to your OTP Authenticator  (after [you made it compatible to my watch](https://github.com/ch1bo/garmin-otp-authenticator/issues/4) — thank you so much again! :pray: ).
What I really liked about OTP Auth, was the very good visual representation how it showed the remaining time:

<p align="center">
<img height="200" src="https://user-images.githubusercontent.com/372620/93743327-2afa7000-fbf0-11ea-9f1e-1414570f4788.png">
<img height="200" src="https://user-images.githubusercontent.com/372620/93743337-2f268d80-fbf0-11ea-9e24-8cebfeadccd4.png">
</p>

Therefore I'm curious whether you would consider implementing a similar visual representation.

**PS:** I'm not sure whether this is relevant, but [the source of OTP Auth is available on GitHub as well](https://github.com/jctim/otp-ciq).

**Comment by shinji** [comment]
#11 #

**Comment by shinji** [comment]
#11

**Comment by ch1bo** [comment]
Thanks to @shinji we have this now on master:
![2020-11-19-172013_413x553_scrot](https://user-images.githubusercontent.com/2621189/99693674-ebcf8a80-2a8b-11eb-844e-46ab944cd419.png)

**Comment by alexanderadam** [comment]
I can close this then, right?

**Comment by ch1bo** [comment]
Yes, I'll release it when I also have #8

**Comment by alexanderadam** [comment]
Awesome. In case nobody wrote this yet: you're a great maintainer 👍
Thank you for your work!

**Comment by alexanderadam** [comment]
Hi Sebastian, do you have any plans when this will be released?

**PS:** No pressure, I'm just curious :wink:

**Comment by ch1bo** [comment]
Had lost my watch for a while, but just found it again. So chances I get to it are higher now 😅 Let's see if I can cut a release with this and some other features on Monday.

**Comment by alexanderadam** [comment]
Oh that's great news (both, that you found your lost watch and that you might have a look on Monday)!

**Comment by ch1bo** [comment]
(I moved to NixOS in the meantime and was having trouble getting the SDK to run yesterday.. but will revisit this on the weekend)
