### ISSUE TITLE
Issues with my Dropbox token

### ISSUE THREAD

**Issue by alexanderadam** [ch1bo/garmin-otp-authenticator#7]
I cannot open the widget anymore after I added my Dropbox token.
It doesn't seem to look special to me but it contains some equal signs in the end (`====`).

**Comment by ch1bo** [comment]
Did you enter the secret via the settings? As `=` is not a valid base32 character the code likely fails when trying to decode that secret.

So the widget does not load up anymore? (Sorry about that) Do you have any non-backed up key material in it?

- If not, please re-install it and try to enter your dropbox secret with only valid base32 characters (here is the alphabet as shown in the device input method: https://github.com/ch1bo/garmin-otp-authenticator/blob/master/src/Alphabet.mc) and let's see if it then works. 

- If yes, I can only fix it earliest tonight (CEST). But would some more info from your end. Is there a crash log saved to the device? (Plug it into a pc and the mass storage access should make files on it accessible)

**Comment by alexanderadam** [comment]
> Did you enter the secret via the settings?

Yes. I copied it.

> `=` is not a valid base32 character

Actually it is. [It's used as the padding character](https://tools.ietf.org/html/rfc3548#section-2.2) in base32, base34, etc.

> So the widget does not load up anymore?

It doesn't load but I can still edit it in the settings dialogue from the phone.
Therefore I was able to remove the key again.

But it fails again when I try to add it.
The Dropbox tokens are the only ones not working so far.

**Comment by ch1bo** [comment]
Alright, I'll forgot to add padding support then :) will fix this and push a fix in the next couple of days.

**Comment by alexanderadam** [comment]
Awesome, thank you! :+1:

**Comment by ch1bo** [comment]
As of version 1.0.4 it should support decoding `=` padding now. However I forgot to add it to the in-app UI alphabet (oops). As you are using the Settings import its not too much of a problem for you, right?

**Comment by alexanderadam** [comment]
> As you are using the Settings import its not too much of a problem for you, right?

excactly :+1:

**Comment by ch1bo** [comment]
Closing this then. Should you have more problems with padding '=' we can re-open this.
