### ISSUE TITLE
I cannot see more than 16 entries

### ISSUE THREAD

**Issue by alexanderadam** [ch1bo/garmin-otp-authenticator#9]
I'm using OTP wherever possible and therefore I have a lot OTP token.
But it seems that it's not showing more than 16 entries in my case.

**Comment by ch1bo** [comment]
Seems like there is an upper limit on the included `Menu` https://developer.garmin.com/connect-iq/api-docs/Toybox/WatchUi/Menu.html. Will have to try the `Menu2` or implement something new for this.

**Comment by alexanderadam** [comment]
Awesome thank you so much for looking into this!

**Comment by ch1bo** [comment]
Just released and published version `1.1.0` which uses `Menu2` when available. So if you have a device with ConnectIQ `> 3.x` you should be able to store many more entries (I tried up to 100).

I will close this, but feel free to re-open if you have still some issues. Also, I'd appreciate a positive review in the garmin store.

**Comment by alexanderadam** [comment]
I just wanted to confirm that it's working perfectly now! Thank you so much!
